# Spring
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: leadmanagement
server:
     port: 8080
     
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger2.json
