package com.bjjimage.model;

import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
@Document(collection = "users")
public class User {

	@ApiModelProperty(value = "The automatic id generated by database")
	@Id
	private String id;

	@ApiModelProperty(value = "The user email")
	@Indexed(unique = true)
	private String email;

	@ApiModelProperty(value = "Password email")
	private String password;

	@ApiModelProperty(value = "User name")
	private String name;

	@ApiModelProperty(value = "User grant authorities ")
	private Set<String> authorities;
	
	

}